spring:
  application:
    name: hexagonal-api
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

maia:
  client:
    address:
      url: http://localhost:8088/api/v1/addresses/find-by-zipcode
