apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.12-alpine3.18
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: app-config
---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-skill
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-skill
  template:
    metadata:
      labels:
        app: api-skill
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8005"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: api-skill
          image: dowglasmaia/admin-skill-api
          ports:
            - containerPort: 8005
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgre:5432/skill
            - name: SPRING_DATASOURCE_USERNAME
              value: "maia"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "maiapw"


---

apiVersion: v1
kind: Service
metadata:
  name: api-skill
spec:
  selector:
    app: api-skill
  ports:
    - port: 80
      targetPort: 8005
  type: LoadBalancer