global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "customer-service-api"
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8009" ]
        labels:
          application: "customer-service-api"

  - job_name: "mongodb_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ['mongodb-exporter:9216']
        labels:
          database: mongodb